# Generated by Django 5.2.10 on 2026-04-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_address_organization_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='custom_fields_config',
            field=models.JSONField(blank=True, default=list, help_text='Global custom fields configuration defined by Admin'),
        ),
        migrations.AddField(
            model_name='parent',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
