# Generated by Django 5.2.10 on 2026-04-06 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_instructor_custom_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='org_custom_fields_config',
            field=models.JSONField(blank=True, default=list, help_text='Manager-defined fields like Class, Section etc.'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
