# Generated by Django 5.2.10 on 2026-04-06 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_org_custom_fields_config_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='instructor',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='instructor_fields_config',
            field=models.JSONField(blank=True, default=list, help_text='Custom fields for instructors'),
        ),
        migrations.AddField(
            model_name='organization',
            name='student_fields_config',
            field=models.JSONField(blank=True, default=list, help_text='Custom fields for students'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='custom_fields_config',
            field=models.JSONField(blank=True, default=list, help_text='Backward compatibility fields'),
        ),
        migrations.AlterField(
            model_name='student',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_mentored', to='core.instructor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='org_custom_fields_config',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classroom'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.classroom')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_subjects', to='core.instructor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.organization')),
            ],
        ),
    ]
