# Generated by Django 5.2.10 on 2026-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_instructor_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='custom_fields_config',
        ),
        migrations.AddField(
            model_name='organization',
            name='is_payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='licensing_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(default='TRIAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='instructor_fields_config',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='organization',
            name='student_fields_config',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
