# Generated by Django 5.2.10 on 2026-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_organization_custom_fields_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='license_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
