# Generated by Django 5.2.10 on 2026-04-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_license_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_license_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_duration_months',
            field=models.IntegerField(default=1),
        ),
    ]
