# Generated by Django 5.2.10 on 2026-04-06 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_timetable_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='organization',
            name='break_after_period',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='organization',
            name='break_duration_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='organization',
            name='period_duration_minutes',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='organization',
            name='school_end_time',
            field=models.TimeField(blank=True, default='15:30:00', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='school_start_time',
            field=models.TimeField(blank=True, default='08:30:00', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='license_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_org', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_duration_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(default='FREE', max_length=50),
        ),
    ]
