# Generated by Django 5.2.10 on 2026-04-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_organization_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='break_after_period',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='break_duration_minutes',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='period_duration_minutes',
            field=models.IntegerField(blank=True, default=45, null=True),
        ),
    ]
