# Generated by Django 5.2.10 on 2026-04-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_organization_break_after_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_intervals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
