# Generated by Django 5.2.10 on 2026-04-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_organization_custom_intervals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='instructor',
        ),
        migrations.AddField(
            model_name='subject',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='taught_subjects', to='core.instructor'),
        ),
    ]
