# Generated by Django 5.2.10 on 2026-04-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_subject_instructor_subject_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
