# Generated by Django 5.2.10 on 2026-04-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_subject_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='core.classroom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Organization Manager'), ('INSTRUCTOR', 'Instructor'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], default='ADMIN', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('CW', 'Classwork'), ('HW', 'Homework'), ('PROJECT', 'Project'), ('ASSIGNMENT', 'Assignment')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='core.classroom')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='core.instructor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='core.organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='core.subject')),
            ],
        ),
    ]
