# Generated by Django 5.2.10 on 2026-04-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_instructor_classrooms_alter_user_role_dailytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
