# Generated by Django 5.2.10 on 2026-04-12 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_organization_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables', to='core.instructor'),
        ),
    ]
